### ISSUE TITLE
Detected code that calls async_forward_entry_setup for integration intesishome

### ISSUE THREAD

**Issue by autumnwalker** [jnimmo/hass-intesishome#15]
This item has started to show up in my Home Assistant logs:

Detected code that calls async_forward_entry_setup for integration intesishome with title: intesishome_local FJ-AC-WIFI-1B (###) and entry_id: 993b9d258d8ad94381b574d97f8f1db4, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Home Assistant Core 2024.8.2
IntesisHome (config flow) 1.0.7

**Comment by Tigerstrength** [comment]
Any news on this topic? 

I see the same messages (and posted it in the wrong place): https://github.com/home-assistant/core/issues/128476
