### ISSUE TITLE
After updating to 1.0.8 integration not working

### ISSUE THREAD

**Issue by mariusnauj** [jnimmo/hass-intesishome#17]
After updating to 1.0.8 integration not working. Tryied to delete integration and add again but "An unknow error appear". I'm using local integration. Rolled back to v. 1.0.7 and everything working fine.

**Comment by autumnwalker** [comment]
@jnimmo did you pull 1.0.8? I only see 1.0.7 as latest.

**Comment by mariusnauj** [comment]
Look:

![image](https://github.com/user-attachments/assets/9d0f41d5-bb3f-4b63-aab9-b31ad3f6df9e)

**Comment by autumnwalker** [comment]
I understand mariusnauj; however, it looks like jnimmo pulled 1.0.8 because of the issue:
![image](https://github.com/user-attachments/assets/053aa085-f18c-47c2-b825-ef38f15a1ef9)

Regardless, I see the issue and I've fixed it. I'll submit another PR.

**Comment by mariusnauj** [comment]
@autumnwalker so now it's safe to update to version 1.0.8 ?

**Comment by autumnwalker** [comment]
@jnimmo will need to pull in my new PR and re-release 1.0.8 before you can update to it.

**Comment by Tigerstrength** [comment]
@jnimmo, any change you can pull in the PR from @autumnwalker? Thanks!

**Comment by autumnwalker** [comment]
This should now be resolved in 3fa2040ce7d1a5e5b5769f14e81ee8dcc01dd774

@mariusnauj can you please confirm / close?

**Comment by mariusnauj** [comment]
Yes, now it's working.
