### ISSUE TITLE
Only one device being pulled in

### ISSUE THREAD

**Issue by addinsella** [jnimmo/hass-intesishome#7]
When I connect to my IntesisHome account only one of my two MHI AC units is pulled into home assistant. Note that when using the "official" HA integration, both AC units are pulled in. There seems to be something wrong with this fork that isn't pulling in all devices from IntesisHome?

Logs show the following entry:

>Logger: homeassistant.components.climate
Source: custom_components/intesishome/climate.py:358
Integration: Climate (documentation, issues)
First occurred: 11:39:23 (1 occurrences)
Last logged: 11:39:23

>intesishome: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/intesishome/climate.py", line 358, in async_update
    self._current_temp = self._controller.get_temperature(self._device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesisbase.py", line 403, in get_temperature
    temperature = self.get_device_property(device_id, "temperature")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesisbase.py", line 193, in get_device_property
    return self._devices[str(device_id)].get(property_name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '206448962216'

**Comment by srkoster** [comment]
I had the same issue today with my intensishome account (although I can't remember having this earlier). I debugged a lot and saw that somewhere in the initialization the first device is created, updated, then added to HA and then connected to the API. The second device gets updated before the first one is connected to the API and somehow, the device list of the controller is empty then, resulting in the above error.

What fixed it for me is disabling the update before add function by changing the following in `custom_components\intensishome\climate.py`

```
if ih_devices := controller.get_devices():
        async_add_entities(
            [
                IntesisAC(ih_device_id, device, controller)
                for ih_device_id, device in ih_devices.items()
            ],
            update_before_add=True,
        )
```
Into
```
if ih_devices := controller.get_devices():
        async_add_entities(
            [
                IntesisAC(ih_device_id, device, controller)
                for ih_device_id, device in ih_devices.items()
            ],
            update_before_add=False,
        )
```

After adding each device to HA, each device is connected to the API and gets updated when the API is called, so no need for the update before add anyway.
